### PR TITLE
fix(#831): Remove anko and eval module pages under scripting

### PR DESCRIPTION
**Pull request by ashnwade**
This PR addresses https://github.com/gravwell/wiki/issues/831

This PR:
- Removes "The Anko Module" and "The Eval Module" pages found here:
image
- Copies some of the documentation from "The Anko Module" to the "Scripting Overview" where there was already a section for "Writing Anko code"
- Updates references to the deleted pages

### CODE REVIEW

**Review by john-floren-gravwell — CHANGES_REQUESTED** [review]
I think we need to keep the old eval.md docs, and *link to them* from the current eval docs page, pointing out that there's an old eval syntax which you may see in old queries.

**Comment by ashnwade** [comment]
The thing about keeping the old eval syntax is that it is expected to appear in a toctree somewhere if it exists. Where do you think it would be appropriate to have it? If I am simply leaving it where it is, should we really be making any changes at all?

**Comment by john-floren-gravwell** [comment]
> The thing about keeping the old eval syntax is that it is expected to appear in a toctree somewhere if it exists. Where do you think it would be appropriate to have it? If I am simply leaving it where it is, should we really be making any changes at all?

Does it have to be in a toctree for technical reasons? If not, I see no problem in referencing it *only* within a few select other pages. It can also appear in searches (I'd suggest we rename the page to "Legacy Eval" or something)

**Comment by ashnwade** [comment]
Ok. I did some additional reading and I did find a special file-wide metadata field (`:orphan:`) that addressed my concerns regarding the toctree. It allows the Legacy Eval file to build but does not produce a toctree warning, basically indicating that this was an intentional decision. 

In addition to moving the Essential and Optional Function Definitions for Anko, I also moved the other content that I had copied from the same file. I thought that since it was all together before, it would be better to keep it together in the new location also. 

I can make additional changes though if this isn't quite right.

**Review by john-floren-gravwell — APPROVED** [review]

**Pull request merged**
