### PR TITLE
chore: 5.4.2 changelog

### PR DESCRIPTION
**Pull request by ashnwade**
This PR addresses no issue. Starting changelog for v5.4.2 release.

### CODE REVIEW

**Comment by ashnwade** [comment]
Would like both a frontend and a backend review

**Review by david-fritz-gravwell — APPROVED** [review]
LGTM

**Review by kris-watts-gravwell — APPROVED** [review]
LGTM

**Review by michael-wisely-gravwell — APPROVED** [review]
LGTM! :+1:

**Pull request merged**
