### PR TITLE
add caveats page and fix some section headings in the hardening doc

### PR DESCRIPTION
**Pull request by floren**

### CODE REVIEW

**Comment by floren** [comment]
closes #104

**Review by djfritz — APPROVED** [review]
LGTM

**Review by djfritz — CHANGES_REQUESTED** [review]
There is no link to the caveats page from anywhere.

**Comment by djfritz** [comment]
Fixes #104

**Comment by floren** [comment]
ptal

**Review by djfritz — APPROVED** [review]
LGTM

**Pull request merged**
