### PR TITLE
Add federators to TOC, and fix red squiggle

### PR DESCRIPTION
**Pull request by john-floren-gravwell**
Addresses #587

### CODE REVIEW

**Review by ashnwade — CHANGES_REQUESTED** [review]
I think that we should delete the file `ingesters/federators/federator.md` and remove it from the toctree near the bottom of `ingesters/ingesters.md`

I don't think it adds much value and I think the navigational flow makes more sense without having it in two places.

image

**Comment by ashnwade** [comment]
The comment about navigation has more to do with how users can navigate with the Previous and Next arrows at the bottom.

**Comment by john-floren-gravwell** [comment]
ptal

**Review by ashnwade — APPROVED** [review]
LGTM

**Pull request merged**
