### PR TITLE
Search bar and search js/api

### PR DESCRIPTION
**Pull request by omoratin**

### CODE REVIEW

**Comment by remasis** [comment]
Looks nice. can I suggest an icon, placeholder text or some other indicator that the bar is for searching?

It appears that the query parameter is preventing the mdwiki javascript from bringing them to the section. I can see how we could use this parameter to highlight or otherwise provide help for the user to see the results they desired. For initial release of this feature we could probably just keep the section headers if that's a bit far of a stretch.

Example:
* search "foobar" and click SFTP example
* URL is http://127.0.0.1:3001/?#!scripting/scriptingsearch.md#SFTP_example?q=foobar and the user is stuck at the top
* change url to http://127.0.0.1:3001/?#!scripting/scriptingsearch.md#SFTP_example and user is directed to the correct section


BACKEND CHANGE FEEDBACK:
can we sort the results to keep changelogs at the bottom or otherwise de-prioritized. I would wager most people using this aren't intending to see results in changelogs

**Comment by michaelwisely** [comment]
I noticed that the search doesn't work at first. Here are the steps I took:

1. Load `localhost:3001`
    - I'm redirected to `http://localhost:3001/#!index.md`
2. Enter "Simple Relay" in the search box, press enter.
    - I'm redirected to `http://localhost:3001/?#!index.md`  (still the home page, but there's a `?` in there now)
3. Enter "Simple Relay" in the search box again, press enter
    - I'm redirected to `http://localhost:3001/?#!search-results.md?q=Simple%20Relay` as expected

Searches after that seem to work as expected.

This seems to be the case for any page. Search doesn't work until you try the first search and get that first `?` in there.

**Comment by michaelwisely** [comment]
I'm seeing a new issue for subsequent searches. Here are the steps I took:

1.  Load the page, and search for "Simple Query"
    - Search results look fine
2.  Enter another search query and press Enter
    - Page is blank

The console says the following:

```
search.js:45 Uncaught TypeError: Cannot read property 'length' of null
    at search (search.js:45)
    at eval (eval at <anonymous> ((index):2), <anonymous>:2:5)
    at eval (<anonymous>)
    at (index):105
    at Function.globalEval ((index):105)
    at HTMLScriptElement.<anonymous> ((index):105)
    at Function.each ((index):105)
    at init.domManip ((index):105)
    at init.append ((index):105)
    at init.<anonymous> ((index):105)
```

**Comment by traetox** [comment]
Might be due to lazy json marshalling.  PR https://github.com/gravwell/wiki/pull/51 should ensure that we don't send null

**Pull request merged**
