### PR TITLE
move join to concat, update image

### PR DESCRIPTION
**Pull request by david-fritz-gravwell**

### CODE REVIEW

**Review by ashnwade — CHANGES_REQUESTED** [review]
The processing modules are listed alphabetically, so `concat` should be moved higher in the list.

**Comment by david-fritz-gravwell** [comment]
@ashnwade PTAL

**Review by ashnwade — CHANGES_REQUESTED** [review]
I missed it the first time I reviewed, but the example is still using `join` instead of `concat` in both the query (text) and the query in the image.

Sorry I missed it before and made you update twice.

**Comment by david-fritz-gravwell** [comment]
Whoops, @ashnwade PTAL

**Review by ashnwade — APPROVED** [review]
LGTM

**Pull request merged**
