### PR TITLE
document else if style statements.

### LINKED ISSUE #1124: Eval: if/else documentation
# Enhancement

## What is the enhancement to be made?
Update the documentation to explicitly state that you can use `else if` as well

## Why should we make this change? (Business justification? What problem is the feature trying to solve?)
Came up as a question and the documentation was not clear that this was possible

### PR DESCRIPTION
**Pull request by david-fritz-gravwell**
Fixes #1124

### CODE REVIEW

**Review by ashnwade — APPROVED** [review]
LGTM

**Review by ashnwade — CHANGES_REQUESTED** [review]
Actually, you put `else if` here, but we use "if" and "else" up above. We should probably be more consistent on using either quotes or backticks.

**Comment by david-fritz-gravwell** [comment]
That's intentional as the syntax we're calling out is specifically `else if`.

**Review by ashnwade — APPROVED** [review]
LGTM

**Pull request merged**
